### ISSUE TITLE
Line breaks from md files are removed 

### ISSUE THREAD

**Issue by ih8snow** [zoni/obsidian-export#55]
Hi Nick;
here's my challenge:

I created a vault with Obsidian v.0.13.17.
The vault contains several folder with *.md notes.

When I use obsidian-export in Linux or Windows 11 everything works fine. I checked the files re to the below mentioned error and I don't see a problem. (line breaks are there)

See screenshot:
![obs-export_2](https://user-images.githubusercontent.com/82544852/147769549-01e114d7-8f8b-49b2-a483-9cb5d46f5be3.png)

Now I use this data to create a static HTML site with mkdocs and the material theme. Using this yml file for a local html.site (following the info on the mkdocs website:

`site_name: Report
site_url: ""
theme: 'material'
use_directory_urls: false
plugins: []`

Again all ok, except that all **line breaks are removed**. (same with different theme)
See Screenshots:
![obsidian-export](https://user-images.githubusercontent.com/82544852/147769276-1f899926-3f75-46b2-b85f-3330bad5ec20.png)

I really have no idea what's going on here, is that something you can fix this with the exporter?
/Jörn

Attached the **test vault** "ExportTest"
[ExportTest.zip](https://github.com/zoni/obsidian-export/files/7793784/ExportTest.zip)

Vault after **obsidian-export**:
[Sitemd_files_after_obs-export.zip](https://github.com/zoni/obsidian-export/files/7793772/Sitemd_files_after_obs-export.zip)

**HTML_Site** after mkdocs export:
[HTML-site.zip](https://github.com/zoni/obsidian-export/files/7793792/HTML-site.zip)

**Comment by zoni** [comment]
Hey @ih8snow,

I suspect you have the option `Strict line breaks` (found under the `Editor` options setting) turned **off** in your Obsidian settings, is that right?

Strictly speaking, Markdown/[CommonMark](https://commonmark.org/), ignores linebreaks. That is, the following text is rendered as a single sentence:

```
This is a line
which is split across multiple lines
in markdown source text.
```

If you want insert hard linebreaks here, there's two ways you can do this with Markdown. The first option is to append two blank spaces (`  `) at the end of the lines:

```
This is a line  
which is split across multiple lines  
in markdown source text.
```

The other option, which I personally prefer and recommend, is to add a backslash at the end of the line:

```
This is a line \
which is split across multiple lines \
in markdown source text.
```

Does that help?

**Comment by zoni** [comment]
Some more good news. :smile: I took a look at the information provided by the [underlying parser](https://github.com/raphlinus/pulldown-cmark), and it turns out it emits [SoftBreak](https://docs.rs/pulldown-cmark/latest/pulldown_cmark/enum.Event.html#variant.SoftBreak) events for these soft linebreaks in your original example.

I'm able to use this information to turn these SoftBreaks into HardBreaks, which should mimic Obsidian's `Strict line breaks` option. With all of the [postprocessor infrastructure](https://docs.rs/obsidian-export/latest/obsidian_export/type.Postprocessor.html) I introduced in [v0.7.0 (2021-04-11)](https://github.com/zoni/obsidian-export/blob/main/CHANGES.md#v070-2021-04-11) this is quite trivial to implement now and I already have a working proof of concept implementation.

I just need to organize this new code properly, hook it up to a CLI argument, add some testcases, etc. so expect a new feature and release with this somewhere over the next week or so.

**Comment by ih8snow** [comment]
> I suspect you have the option `Strict line breaks` (found under the `Editor` options setting) turned **off** in your Obsidian settings, is that right?

Hi,
you are correct. I'm using these settings. Thanks for your explanation, that definitely helps. I was not really sure what these settings will cause in the work with obsidian, but now I can see it more clear.

**Comment by ih8snow** [comment]
> I'm able to use this information to turn these SoftBreaks into HardBreaks, which should mimic Obsidian's `Strict line breaks` option.

That is super cool! Great news at the end of the year.
I'll test with the above-mentioned settings and of course wait for the new version.
Many thanks for your support!

**Comment by zoni** [comment]
Happy new year! [v22.1.0](https://github.com/zoni/obsidian-export/releases/tag/v22.1.0) is out now with a new `--hard-linebreaks` CLI argument. It appears to work as intended on my basic, exploratory testing, but please feel free to let me know if you run into unexpected issues on a real vault.

**Comment by ih8snow** [comment]
Thanks!!!
