### ISSUE TITLE
Allow different project organization

### ISSUE THREAD

**Issue by SR-G** [zoni/obsidian-export#8]
I would like to have this structure : 

In my obsidian workspace : 
```
.obsidian
daily/
resources/
hugo/
```

"daily/" are my .md files
"resources/" are where my images are
"hugo/" is my hugo workspace, with a regular structure
"hugo/content/" : the output of `obsidian-export`
"hugo/layouts/" : hugo regular layout folder 
(and so on, for themes, ...)

With that organization : 
- my hugo workspace is clearly separated from my obsidian workspace (in a sub-folder)
- yet this hugo workspace is very standard (nothing to toy around)

However my problem is that right now, one extra layer is missing in the path generated between converted markdown files and resources.
Maybe this is coming by the fact that my target folder (second parameter of `obsidian-export` has two levels ? ("hugo/content/") ? Or because i have subfolders in "daily/" and "resources/" ?
"daily/2021/01.md"
"resources/2021/images/Pasted Image.png"

For now, as a result, i have (not takin #7 in account here) : 
`![Pasted image 20210201170521.png](..\..\resources\2021\images\Pasted%20image%2020210201170521.png)`

And images are not generated by hugo.

Whereas with an extra path, images are correctly displayed : 

`![Pasted image 20210201170521.png](..\..\..\resources\2021\images\Pasted%20image%2020210201170521.png)`

**Comment by zoni** [comment]
The problem here is Hugo. Not to pick on Hugo too much, I use it too and really like it in general, but in this regard I find its behavior quite unfortunate. Hugo expects you to use [`ref` and `relref` shortcodes](https://gohugo.io/content-management/cross-references/) instead of using regular Markdown link syntax to sibling content files.

(If you try the exact same file layout with [MkDocs](https://www.mkdocs.org/), you'll find it works out of the box without issue)

I've found that [Markdown Render Hooks](https://gohugo.io/getting-started/configuration-markup#markdown-render-hooks) allow us to work around the issue (make sure you're using `goldmark` as your renderer).

Create the file `layouts/_default/_markup/render-link.html` with the following contents:

```
{{- $url := urls.Parse .Destination -}}
{{- $scheme := $url.Scheme -}}

<a href="
  {{- if eq $scheme "" -}}
    {{- if strings.HasSuffix $url.Path ".md" -}}
      {{- relref .Page .Destination | safeURL -}}
    {{- else -}}
      {{- .Destination | safeURL -}}
    {{- end -}}
  {{- else -}}
    {{- .Destination | safeURL -}}
  {{- end -}}"
  {{- with .Title }} title="{{ . | safeHTML }}"{{- end -}}>
  {{- .Text | safeHTML -}}
</a>

{{- /* whitespace stripped here to avoid trailing newline in rendered result caused by file EOL */ -}}
```

And `layouts/_default/_markup/render-image.html` for images:

```
{{- $url := urls.Parse .Destination -}}
{{- $scheme := $url.Scheme -}}

<img src="
  {{- if eq $scheme "" -}}
    {{- if strings.HasSuffix $url.Path ".md" -}}
      {{- relref .Page .Destination | safeURL -}}
    {{- else -}}
      {{- printf "/%s%s" .Page.File.Dir .Destination | safeURL -}}
    {{- end -}}
  {{- else -}}
    {{- .Destination | safeURL -}}
  {{- end -}}"
  {{- with .Title }} title="{{ . | safeHTML }}"{{- end -}}
  {{- with .Text }} alt="{{ . | safeHTML }}"
  {{- end -}}
/>

{{- /* whitespace stripped here to avoid trailing newline in rendered result caused by file EOL */ -}}
```

Does that resolve the issue for you?

**Comment by zoni** [comment]
Based on the lack of response I'm going to assume you either fixed your issue or lost interest in pursuing this.

**Comment by ikrima** [comment]
> 
> 
> Based on the lack of response I'm going to assume you either fixed your issue or lost interest in pursuing this.

apologies for necro-ing this but ran into this same issue with mkdocs. Not too familiar with hugo but fwiw, the issue was the generated relative paths on windows were using unescaped "\" as path separator 

Swapping them with "/" fixed the issue

**Comment by JeremieLitzler** [comment]
@zoni 

Thanks for this solution. That made my day! I was horrified to have to change all native markdown links to `< ref ... >` or `< relref ... >`...

It works like a charm.
