### ISSUE TITLE
Is there an easy way to add a title attribute to the frontmatter based on the path?

### ISSUE THREAD

**Issue by brandonkboswell** [zoni/obsidian-export#84]

**Comment by zoni** [comment]
When you consume the underlying API instead of the final CLI interface, it's quite straightforward to add a [postprocessor](https://docs.rs/obsidian-export/latest/obsidian_export/type.Postprocessor.html) with your custom logic for this.

The downside of course is that you'd have to write some Rust, as well as redo the [CLI parts](https://github.com/zoni/obsidian-export/blob/main/src/main.rs) yourself.

If there was a sufficiently general use-case for this I'd be open to bundling a built-in postprocessor for this, exposed via a CLI argument, but I doubt it could be made generic enough to be worth including.
